### ISSUE TITLE
Add wall collision detection when pushing a robot

### ISSUE THREAD

**Issue by fmerlung** [DTU-software-s-bedste-studenter/Roborally#2]
Currently collisions are only detected when a robot is moving as a result of a command card. Collisions with walls should also be detected so pushing a robot only becomes possible when there's no wall blocking the path a robot is being pushed. Perhaps this should be done recursively, as a type of 'look-ahead' where before any robots are being moved, a method looks ahead and checks if the move is not being blocked.

**Comment by andelsbolig** [comment]
Remember [Javadoc](https://github.com/DTU-software-s-bedste-studenter/Roborally/issues/18)
