### ISSUE TITLE
Load game - JSON

### ISSUE THREAD

**Issue by andelsbolig** [DTU-software-s-bedste-studenter/Roborally#4]
Depends on [Save Game](https://github.com/DTU-software-s-bedste-studenter/Roborally/issues/3)

Load game with JSON/GSON

**Comment by andelsbolig** [comment]
Remember [Javadoc](https://github.com/DTU-software-s-bedste-studenter/Roborally/issues/18)

**Comment by SkumJustEatMe** [comment]
Done
