### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by SkumJustEatMe** [DTU-software-s-bedste-studenter/Roborally#8]
Depends on:

You must reach checkpoints in
numerical order. In order to reach
a checkpoint, you must be on it at
the end of a register, and you may
enter a checkpoint from any side.
After you reach a checkpoint, take
a checkpoint token, and place it
on your player mat to track your
progress in the race.

**Comment by andelsbolig** [comment]
Remember [Javadoc](https://github.com/DTU-software-s-bedste-studenter/Roborally/issues/18)
