### ISSUE TITLE
Push Panels

### ISSUE THREAD

**Issue by SkumJustEatMe** [DTU-software-s-bedste-studenter/Roborally#9]
Depends on:

Push panels push any robot
resting on them into the next
space in the direction the push
panel faces. The panels activate
only in the register that corresponds to the number on them.

**Comment by andelsbolig** [comment]
Remember [Javadoc](https://github.com/DTU-software-s-bedste-studenter/Roborally/issues/18)

**Comment by SkumJustEatMe** [comment]
Done
